export const LOAD_HITOKOTO = 'app/Home/CHANGE_USERNAME/LOAD_HITOKOTO';
export const LOAD_HITOKOTO_SUCCESS = 'app/Home/CHANGE_USERNAME/LOAD_HITOKOTO_SUCCESS';
export const LOAD_HITOKOTO_ERROR = 'app/Home/CHANGE_USERNAME/LOAD_HITOKOTO_ERROR';
